#import <Foundation/NSString.h>
#import <AppKit/AppKitExport.h>

APPKIT_EXPORT NSString *NSAccessibilityChildrenAttribute;
APPKIT_EXPORT NSString *NSAccessibilityContentsAttribute;
APPKIT_EXPORT NSString *NSAccessibilityDescriptionAttribute;
APPKIT_EXPORT NSString *NSAccessibilityEnabledAttribute;
APPKIT_EXPORT NSString *NSAccessibilityFocusedAttribute;
APPKIT_EXPORT NSString *NSAccessibilityHelpAttribute;
APPKIT_EXPORT NSString *NSAccessibilityMaxValueAttribute;
APPKIT_EXPORT NSString *NSAccessibilityMinValueAttribute;
APPKIT_EXPORT NSString *NSAccessibilityParentAttribute;
APPKIT_EXPORT NSString *NSAccessibilityPositionAttribute;
APPKIT_EXPORT NSString *NSAccessibilityRoleAttribute;
APPKIT_EXPORT NSString *NSAccessibilityRoleDescriptionAttribute;
APPKIT_EXPORT NSString *NSAccessibilitySelectedChildrenAttribute;
APPKIT_EXPORT NSString *NSAccessibilityShownMenuAttribute;
APPKIT_EXPORT NSString *NSAccessibilitySizeAttribute;
APPKIT_EXPORT NSString *NSAccessibilitySubroleAttribute;
APPKIT_EXPORT NSString *NSAccessibilityTitleAttribute;
APPKIT_EXPORT NSString *NSAccessibilityTopLevelUIElementAttribute;
APPKIT_EXPORT NSString *NSAccessibilityValueAttribute;
APPKIT_EXPORT NSString *NSAccessibilityValueDescriptionAttribute;
APPKIT_EXPORT NSString *NSAccessibilityVisibleChildrenAttribute;
APPKIT_EXPORT NSString *NSAccessibilityWindowAttribute;

APPKIT_EXPORT NSString *NSAccessibilityInsertionPointLineNumberAttribute;
APPKIT_EXPORT NSString *NSAccessibilityNumberOfCharactersAttribute;
APPKIT_EXPORT NSString *NSAccessibilitySelectedTextAttribute;
APPKIT_EXPORT NSString *NSAccessibilitySelectedTextRangeAttribute;
APPKIT_EXPORT NSString *NSAccessibilitySelectedTextRangesAttribute;
APPKIT_EXPORT NSString *NSAccessibilitySharedCharacterRangeAttribute;
APPKIT_EXPORT NSString *NSAccessibilitySharedTextUIElementsAttribute;
APPKIT_EXPORT NSString *NSAccessibilityVisibleCharacterRangeAttribute;

APPKIT_EXPORT NSString *NSAccessibilityAttributedStringForRangeParameterizedAttribute;
APPKIT_EXPORT NSString *NSAccessibilityBoundsForRangeParameterizedAttribute;
APPKIT_EXPORT NSString *NSAccessibilityLineForIndexParameterizedAttribute;
APPKIT_EXPORT NSString *NSAccessibilityRTFForRangeParameterizedAttribute;
APPKIT_EXPORT NSString *NSAccessibilityRangeForIndexParameterizedAttribute;
APPKIT_EXPORT NSString *NSAccessibilityRangeForLineParameterizedAttribute;
APPKIT_EXPORT NSString *NSAccessibilityRangeForPositionParameterizedAttribute;
APPKIT_EXPORT NSString *NSAccessibilityStringForRangeParameterizedAttribute;
APPKIT_EXPORT NSString *NSAccessibilityStyleRangeForIndexParameterizedAttribute;

APPKIT_EXPORT NSString *NSAccessibilityAttachmentTextAttribute;
APPKIT_EXPORT NSString *NSAccessibilityBackgroundColorTextAttribute;
APPKIT_EXPORT NSString *NSAccessibilityFontFamilyKey;
APPKIT_EXPORT NSString *NSAccessibilityFontNameKey;
APPKIT_EXPORT NSString *NSAccessibilityFontSizeKey;
APPKIT_EXPORT NSString *NSAccessibilityFontTextAttribute;
APPKIT_EXPORT NSString *NSAccessibilityForegroundColorTextAttribute;
APPKIT_EXPORT NSString *NSAccessibilityLinkTextAttribute;
APPKIT_EXPORT NSString *NSAccessibilityMisspelledTextAttribute;
APPKIT_EXPORT NSString *NSAccessibilityShadowTextAttribute;
APPKIT_EXPORT NSString *NSAccessibilityStrikethroughColorTextAttribute;
APPKIT_EXPORT NSString *NSAccessibilityStrikethroughTextAttribute;
APPKIT_EXPORT NSString *NSAccessibilitySuperscriptTextAttribute;
APPKIT_EXPORT NSString *NSAccessibilityUnderlineColorTextAttribute;
APPKIT_EXPORT NSString *NSAccessibilityUnderlineTextAttribute;
APPKIT_EXPORT NSString *NSAccessibilityVisibleNameKey;

APPKIT_EXPORT NSString *NSAccessibilityCancelButtonAttribute;
APPKIT_EXPORT NSString *NSAccessibilityCloseButtonAttribute;
APPKIT_EXPORT NSString *NSAccessibilityDefaultButtonAttribute;
APPKIT_EXPORT NSString *NSAccessibilityGrowAreaAttribute;
APPKIT_EXPORT NSString *NSAccessibilityMainAttribute;
APPKIT_EXPORT NSString *NSAccessibilityMinimizeButtonAttribute;
APPKIT_EXPORT NSString *NSAccessibilityMinimizedAttribute;
APPKIT_EXPORT NSString *NSAccessibilityModalAttribute;
APPKIT_EXPORT NSString *NSAccessibilityProxyAttribute;
APPKIT_EXPORT NSString *NSAccessibilityToolbarButtonAttribute;
APPKIT_EXPORT NSString *NSAccessibilityZoomButtonAttribute;

APPKIT_EXPORT NSString *NSAccessibilityHorizontalOrientationValue;
APPKIT_EXPORT NSString *NSAccessibilityVerticalOrientationValue;
APPKIT_EXPORT NSString *NSAccessibilityUnknownOrientationValue;

APPKIT_EXPORT NSString *NSAccessibilityClearButtonAttribute;
APPKIT_EXPORT NSString *NSAccessibilityColumnTitlesAttribute;
APPKIT_EXPORT NSString *NSAccessibilityFocusedUIElementAttribute;
APPKIT_EXPORT NSString *NSAccessibilityFocusedWindowAttribute;
APPKIT_EXPORT NSString *NSAccessibilityFrontmostAttribute;
APPKIT_EXPORT NSString *NSAccessibilityHiddenAttribute;
APPKIT_EXPORT NSString *NSAccessibilityMainWindowAttribute;
APPKIT_EXPORT NSString *NSAccessibilityMenuBarAttribute;
APPKIT_EXPORT NSString *NSAccessibilityOrientationAttribute;
APPKIT_EXPORT NSString *NSAccessibilitySearchButtonAttribute;
APPKIT_EXPORT NSString *NSAccessibilitySearchMenuAttribute;
APPKIT_EXPORT NSString *NSAccessibilityWindowsAttribute;

APPKIT_EXPORT NSString *NSAccessibilityColumnCountAttribute;
APPKIT_EXPORT NSString *NSAccessibilityOrderedByRowAttribute;
APPKIT_EXPORT NSString *NSAccessibilityRowCountAttribute;

APPKIT_EXPORT NSString *NSAccessibilityColumnHeaderUIElementsAttribute;
APPKIT_EXPORT NSString *NSAccessibilityColumnsAttribute;
APPKIT_EXPORT NSString *NSAccessibilityRowHeaderUIElementsAttribute;
APPKIT_EXPORT NSString *NSAccessibilityRowsAttribute;
APPKIT_EXPORT NSString *NSAccessibilitySelectedColumnsAttribute;
APPKIT_EXPORT NSString *NSAccessibilitySelectedRowsAttribute;
APPKIT_EXPORT NSString *NSAccessibilitySortDirectionAttribute;
APPKIT_EXPORT NSString *NSAccessibilityVisibleColumnsAttribute;
APPKIT_EXPORT NSString *NSAccessibilityVisibleRowsAttribute;

APPKIT_EXPORT NSString *NSAccessibilityDisclosedByRowAttribute;
APPKIT_EXPORT NSString *NSAccessibilityDisclosedRowsAttribute;
APPKIT_EXPORT NSString *NSAccessibilityDisclosingAttribute;
APPKIT_EXPORT NSString *NSAccessibilityDisclosureLevelAttribute;

APPKIT_EXPORT NSString *NSAccessibilitySelectedCellsAttribute;
APPKIT_EXPORT NSString *NSAccessibilityVisibleCellsAttribute;

APPKIT_EXPORT NSString *NSAccessibilityCellForColumnAndRowParameterizedAttribute;

APPKIT_EXPORT NSString *NSAccessibilityRowIndexRangeAttribute;
APPKIT_EXPORT NSString *NSAccessibilityColumnIndexRangeAttribute;

APPKIT_EXPORT NSString *NSAccessibilityAscendingSortDirectionValue;
APPKIT_EXPORT NSString *NSAccessibilityDescendingSortDirectionValue;
APPKIT_EXPORT NSString *NSAccessibilityUnknownSortDirectionValue;

APPKIT_EXPORT NSString *NSAccessibilityHorizontalUnitsAttribute;
APPKIT_EXPORT NSString *NSAccessibilityVerticalUnitsAttribute;
APPKIT_EXPORT NSString *NSAccessibilityHorizontalUnitDescriptionAttribute;
APPKIT_EXPORT NSString *NSAccessibilityVerticalUnitDescriptionAttribute;

APPKIT_EXPORT NSString *NSAccessibilityLayoutPointForScreenPointParameterizedAttribute;
APPKIT_EXPORT NSString *NSAccessibilityLayoutSizeForScreenSizeParameterizedAttribute;
APPKIT_EXPORT NSString *NSAccessibilityScreenPointForLayoutPointParameterizedAttribute;
APPKIT_EXPORT NSString *NSAccessibilityScreenSizeForLayoutSizeParameterizedAttribute;

APPKIT_EXPORT NSString *NSAccessibilityHandlesAttribute;

APPKIT_EXPORT NSString *NSAccessibilityAllowedValuesAttribute;
APPKIT_EXPORT NSString *NSAccessibilityLabelUIElementsAttribute;
APPKIT_EXPORT NSString *NSAccessibilityLabelValueAttribute;

APPKIT_EXPORT NSString *NSAccessibilityMatteContentUIElementAttribute;
APPKIT_EXPORT NSString *NSAccessibilityMatteHoleAttribute;

APPKIT_EXPORT NSString *NSAccessibilityMarkerGroupUIElementAttribute;
APPKIT_EXPORT NSString *NSAccessibilityMarkerTypeAttribute;
APPKIT_EXPORT NSString *NSAccessibilityMarkerTypeDescriptionAttribute;
APPKIT_EXPORT NSString *NSAccessibilityMarkerUIElementsAttribute;
APPKIT_EXPORT NSString *NSAccessibilityMarkerValuesAttribute;
APPKIT_EXPORT NSString *NSAccessibilityUnitDescriptionAttribute;
APPKIT_EXPORT NSString *NSAccessibilityUnitsAttribute;

APPKIT_EXPORT NSString *NSAccessibilityCenterTabStopMarkerTypeValue;
APPKIT_EXPORT NSString *NSAccessibilityDecimalTabStopMarkerTypeValue;
APPKIT_EXPORT NSString *NSAccessibilityFirstLineIndentMarkerTypeValue;
APPKIT_EXPORT NSString *NSAccessibilityHeadIndentMarkerTypeValue;
APPKIT_EXPORT NSString *NSAccessibilityLeftTabStopMarkerTypeValue;
APPKIT_EXPORT NSString *NSAccessibilityRightTabStopMarkerTypeValue;
APPKIT_EXPORT NSString *NSAccessibilityTailIndentMarkerTypeValue;
APPKIT_EXPORT NSString *NSAccessibilityUnknownMarkerTypeValue;

APPKIT_EXPORT NSString *NSAccessibilityCentimetersUnitValue;
APPKIT_EXPORT NSString *NSAccessibilityInchesUnitValue;
APPKIT_EXPORT NSString *NSAccessibilityPicasUnitValue;
APPKIT_EXPORT NSString *NSAccessibilityPointsUnitValue;
APPKIT_EXPORT NSString *NSAccessibilityUnknownUnitValue;

APPKIT_EXPORT NSString *NSAccessibilityLinkedUIElementsAttribute;
APPKIT_EXPORT NSString *NSAccessibilityServesAsTitleForUIElementsAttribute;
APPKIT_EXPORT NSString *NSAccessibilityTitleUIElementAttribute;

APPKIT_EXPORT NSString *NSAccessibilityDecrementButtonAttribute;
APPKIT_EXPORT NSString *NSAccessibilityDocumentAttribute;
APPKIT_EXPORT NSString *NSAccessibilityEditedAttribute;
APPKIT_EXPORT NSString *NSAccessibilityExpandedAttribute;
APPKIT_EXPORT NSString *NSAccessibilityFilenameAttribute;
APPKIT_EXPORT NSString *NSAccessibilityHeaderAttribute;
APPKIT_EXPORT NSString *NSAccessibilityHorizontalScrollBarAttribute;
APPKIT_EXPORT NSString *NSAccessibilityIncrementButtonAttribute;
APPKIT_EXPORT NSString *NSAccessibilityIndexAttribute;
APPKIT_EXPORT NSString *NSAccessibilityNextContentsAttribute;
APPKIT_EXPORT NSString *NSAccessibilityOverflowButtonAttribute;
APPKIT_EXPORT NSString *NSAccessibilityPreviousContentsAttribute;
APPKIT_EXPORT NSString *NSAccessibilitySelectedAttribute;
APPKIT_EXPORT NSString *NSAccessibilitySplittersAttribute;
APPKIT_EXPORT NSString *NSAccessibilityTabsAttribute;
APPKIT_EXPORT NSString *NSAccessibilityURLAttribute;
APPKIT_EXPORT NSString *NSAccessibilityVerticalScrollBarAttribute;
APPKIT_EXPORT NSString *NSAccessibilityWarningValueAttribute;
APPKIT_EXPORT NSString *NSAccessibilityCriticalValueAttribute;
APPKIT_EXPORT NSString *NSAccessibilityPlaceholderValueAttribute;

APPKIT_EXPORT NSString *NSAccessibilityApplicationRole;
APPKIT_EXPORT NSString *NSAccessibilityBrowserRole;
APPKIT_EXPORT NSString *NSAccessibilityBusyIndicatorRole;
APPKIT_EXPORT NSString *NSAccessibilityButtonRole;
APPKIT_EXPORT NSString *NSAccessibilityCellRole;
APPKIT_EXPORT NSString *NSAccessibilityCheckBoxRole;
APPKIT_EXPORT NSString *NSAccessibilityColorWellRole;
APPKIT_EXPORT NSString *NSAccessibilityColumnRole;
APPKIT_EXPORT NSString *NSAccessibilityComboBoxRole;
APPKIT_EXPORT NSString *NSAccessibilityDisclosureTriangleRole;
APPKIT_EXPORT NSString *NSAccessibilityDrawerRole;
APPKIT_EXPORT NSString *NSAccessibilityGridRole;
APPKIT_EXPORT NSString *NSAccessibilityGroupRole;
APPKIT_EXPORT NSString *NSAccessibilityGrowAreaRole;
APPKIT_EXPORT NSString *NSAccessibilityHandleRole;
APPKIT_EXPORT NSString *NSAccessibilityHelpTagRole;
APPKIT_EXPORT NSString *NSAccessibilityImageRole;
APPKIT_EXPORT NSString *NSAccessibilityIncrementorRole;
APPKIT_EXPORT NSString *NSAccessibilityLayoutAreaRole;
APPKIT_EXPORT NSString *NSAccessibilityLayoutItemRole;
APPKIT_EXPORT NSString *NSAccessibilityLinkRole;
APPKIT_EXPORT NSString *NSAccessibilityListRole;
APPKIT_EXPORT NSString *NSAccessibilityMatteRole;
APPKIT_EXPORT NSString *NSAccessibilityMenuBarRole;
APPKIT_EXPORT NSString *NSAccessibilityMenuButtonRole;
APPKIT_EXPORT NSString *NSAccessibilityMenuItemRole;
APPKIT_EXPORT NSString *NSAccessibilityMenuRole;
APPKIT_EXPORT NSString *NSAccessibilityOutlineRole;
APPKIT_EXPORT NSString *NSAccessibilityPopUpButtonRole;
APPKIT_EXPORT NSString *NSAccessibilityProgressIndicatorRole;
APPKIT_EXPORT NSString *NSAccessibilityRadioButtonRole;
APPKIT_EXPORT NSString *NSAccessibilityRadioGroupRole;
APPKIT_EXPORT NSString *NSAccessibilityRelevanceIndicatorRole;
APPKIT_EXPORT NSString *NSAccessibilityRowRole;
APPKIT_EXPORT NSString *NSAccessibilityRulerMarkerRole;
APPKIT_EXPORT NSString *NSAccessibilityRulerRole;
APPKIT_EXPORT NSString *NSAccessibilityScrollAreaRole;
APPKIT_EXPORT NSString *NSAccessibilityScrollBarRole;
APPKIT_EXPORT NSString *NSAccessibilitySheetRole;
APPKIT_EXPORT NSString *NSAccessibilitySliderRole;
APPKIT_EXPORT NSString *NSAccessibilitySortButtonRole;
APPKIT_EXPORT NSString *NSAccessibilitySplitGroupRole;
APPKIT_EXPORT NSString *NSAccessibilitySplitterRole;
APPKIT_EXPORT NSString *NSAccessibilityStaticTextRole;
APPKIT_EXPORT NSString *NSAccessibilitySystemWideRole;
APPKIT_EXPORT NSString *NSAccessibilityTabGroupRole;
APPKIT_EXPORT NSString *NSAccessibilityTableRole;
APPKIT_EXPORT NSString *NSAccessibilityTextAreaRole;
APPKIT_EXPORT NSString *NSAccessibilityTextFieldRole;
APPKIT_EXPORT NSString *NSAccessibilityToolbarRole;
APPKIT_EXPORT NSString *NSAccessibilityUnknownRole;
APPKIT_EXPORT NSString *NSAccessibilityValueIndicatorRole;
APPKIT_EXPORT NSString *NSAccessibilityWindowRole;

APPKIT_EXPORT NSString *NSAccessibilityCloseButtonSubrole;
APPKIT_EXPORT NSString *NSAccessibilityDecrementArrowSubrole;
APPKIT_EXPORT NSString *NSAccessibilityDecrementPageSubrole;
APPKIT_EXPORT NSString *NSAccessibilityDialogSubrole;
APPKIT_EXPORT NSString *NSAccessibilityFloatingWindowSubrole;
APPKIT_EXPORT NSString *NSAccessibilityIncrementArrowSubrole;
APPKIT_EXPORT NSString *NSAccessibilityIncrementPageSubrole;
APPKIT_EXPORT NSString *NSAccessibilityMinimizeButtonSubrole;
APPKIT_EXPORT NSString *NSAccessibilityOutlineRowSubrole;
APPKIT_EXPORT NSString *NSAccessibilitySearchFieldSubrole;
APPKIT_EXPORT NSString *NSAccessibilitySecureTextFieldSubrole;
APPKIT_EXPORT NSString *NSAccessibilityStandardWindowSubrole;
APPKIT_EXPORT NSString *NSAccessibilitySystemDialogSubrole;
APPKIT_EXPORT NSString *NSAccessibilitySystemFloatingWindowSubrole;
APPKIT_EXPORT NSString *NSAccessibilityTableRowSubrole;
APPKIT_EXPORT NSString *NSAccessibilityTextAttachmentSubrole;
APPKIT_EXPORT NSString *NSAccessibilityTextLinkSubrole;
APPKIT_EXPORT NSString *NSAccessibilityTimelineSubrole;
APPKIT_EXPORT NSString *NSAccessibilityToolbarButtonSubrole;
APPKIT_EXPORT NSString *NSAccessibilityUnknownSubrole;
APPKIT_EXPORT NSString *NSAccessibilityZoomButtonSubrole;
APPKIT_EXPORT NSString *NSAccessibilitySortButtonSubrole;
APPKIT_EXPORT NSString *NSAccessibilityRatingIndicatorSubrole;
APPKIT_EXPORT NSString *NSAccessibilityContentListSubrole;
APPKIT_EXPORT NSString *NSAccessibilityDefinitionListSubrole;


APPKIT_EXPORT NSString *NSAccessibilityCancelAction;
APPKIT_EXPORT NSString *NSAccessibilityConfirmAction;
APPKIT_EXPORT NSString *NSAccessibilityDecrementAction;
APPKIT_EXPORT NSString *NSAccessibilityDeleteAction;
APPKIT_EXPORT NSString *NSAccessibilityIncrementAction;
APPKIT_EXPORT NSString *NSAccessibilityPickAction;
APPKIT_EXPORT NSString *NSAccessibilityPressAction;
APPKIT_EXPORT NSString *NSAccessibilityRaiseAction;
APPKIT_EXPORT NSString *NSAccessibilityShowMenuAction;

APPKIT_EXPORT NSString *NSAccessibilityMainWindowChangedNotification;
APPKIT_EXPORT NSString *NSAccessibilityFocusedWindowChangedNotification;
APPKIT_EXPORT NSString *NSAccessibilityFocusedUIElementChangedNotification;

APPKIT_EXPORT NSString *NSAccessibilityWindowCreatedNotification;
APPKIT_EXPORT NSString *NSAccessibilityWindowDeminiaturizedNotification;
APPKIT_EXPORT NSString *NSAccessibilityWindowMiniaturizedNotification;
APPKIT_EXPORT NSString *NSAccessibilityWindowMovedNotification;
APPKIT_EXPORT NSString *NSAccessibilityWindowResizedNotification;

APPKIT_EXPORT NSString *NSAccessibilityApplicationActivatedNotification;
APPKIT_EXPORT NSString *NSAccessibilityApplicationDeactivatedNotification;
APPKIT_EXPORT NSString *NSAccessibilityApplicationHiddenNotification;
APPKIT_EXPORT NSString *NSAccessibilityApplicationShownNotification;

APPKIT_EXPORT NSString *NSAccessibilityDrawerCreatedNotification;
APPKIT_EXPORT NSString *NSAccessibilitySheetCreatedNotification;

APPKIT_EXPORT NSString *NSAccessibilityCreatedNotification;
APPKIT_EXPORT NSString *NSAccessibilityMovedNotification;
APPKIT_EXPORT NSString *NSAccessibilityResizedNotification;
APPKIT_EXPORT NSString *NSAccessibilityTitleChangedNotification;
APPKIT_EXPORT NSString *NSAccessibilityUIElementDestroyedNotification;
APPKIT_EXPORT NSString *NSAccessibilityValueChangedNotification;

APPKIT_EXPORT NSString *NSAccessibilityHelpTagCreatedNotification;
APPKIT_EXPORT NSString *NSAccessibilityRowCountChangedNotification;
APPKIT_EXPORT NSString *NSAccessibilitySelectedChildrenChangedNotification;
APPKIT_EXPORT NSString *NSAccessibilitySelectedColumnsChangedNotification;
APPKIT_EXPORT NSString *NSAccessibilitySelectedRowsChangedNotification;
APPKIT_EXPORT NSString *NSAccessibilitySelectedTextChangedNotification;
APPKIT_EXPORT NSString *NSAccessibilityRowExpandedNotification;
APPKIT_EXPORT NSString *NSAccessibilityRowCollapsedNotification;
APPKIT_EXPORT NSString *NSAccessibilitySelectedCellsChangedNotification;
APPKIT_EXPORT NSString *NSAccessibilityUnitsChangedNotification;
APPKIT_EXPORT NSString *NSAccessibilitySelectedChildrenMovedNotification;

APPKIT_EXPORT NSString *NSAccessibilityErrorCodeExceptionInfo;

APPKIT_EXPORT void NSAccessibilityPostNotification (
   id element,
   NSString *notification
);

APPKIT_EXPORT NSString * NSAccessibilityRoleDescription (
   NSString *role,
   NSString *subrole
);

APPKIT_EXPORT id NSAccessibilityUnignoredAncestor (
   id element
);

@interface NSObject(NSAccessibility)
-(NSArray *)accessibilityAttributeNames;
-accessibilityAttributeValue:(NSString *)attribute;
@end
